# Generated by Django 3.0.4 on 2020-03-29 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('users', models.CharField(max_length=200)),
                ('proteins', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('kcal_quantity', models.IntegerField()),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
