# Generated by Django 3.0.4 on 2020-04-02 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReduceKcal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
