# Generated by Django 3.0.4 on 2020-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_reducekcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducekcal',
            name='users',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
